package com.lqq.supportflow.knowledge.api;
import com.lqq.supportflow.knowledge.application.*; import com.lqq.supportflow.knowledge.domain.*; import com.lqq.supportflow.shared.AuthenticatedPrincipal; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/admin/knowledge-bases/{knowledgeBaseId}/documents") public class AdminKnowledgeDocumentController { private final RegisterKnowledgeDocumentService service; private final GetDocumentIngestionProgressService progress; private final UploadKnowledgeDocumentService uploads; private final IndexKnowledgeDocumentService indexing; private final RetryKnowledgeDocumentService retry; private final RebuildKnowledgeIndexService rebuild; public AdminKnowledgeDocumentController(RegisterKnowledgeDocumentService service,GetDocumentIngestionProgressService progress,UploadKnowledgeDocumentService uploads,IndexKnowledgeDocumentService indexing,RetryKnowledgeDocumentService retry,RebuildKnowledgeIndexService rebuild){this.service=service;this.progress=progress;this.uploads=uploads;this.indexing=indexing;this.retry=retry;this.rebuild=rebuild;}
 @PostMapping ResponseEntity<KnowledgeDocument> register(@AuthenticationPrincipal AuthenticatedPrincipal p,@PathVariable Long knowledgeBaseId,@Valid @RequestBody RegisterKnowledgeDocumentRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.register(p.tenantId(),knowledgeBaseId,r.fileName(),r.content()));}
 @PostMapping(value="/upload",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<KnowledgeDocument> upload(@AuthenticationPrincipal AuthenticatedPrincipal p,@PathVariable Long knowledgeBaseId,@RequestPart("file") org.springframework.web.multipart.MultipartFile file){return ResponseEntity.status(HttpStatus.CREATED).body(uploads.upload(p.tenantId(),knowledgeBaseId,file));}
 @PostMapping("/{documentId}/index") KnowledgeDocument index(@AuthenticationPrincipal AuthenticatedPrincipal p,@PathVariable Long knowledgeBaseId,@PathVariable Long documentId){return indexing.index(p.tenantId(),knowledgeBaseId,documentId);}
 @PostMapping("/{documentId}/retry") KnowledgeDocument retry(@AuthenticationPrincipal AuthenticatedPrincipal p,@PathVariable Long knowledgeBaseId,@PathVariable Long documentId){return retry.retry(p.tenantId(),knowledgeBaseId,documentId);}
 @PostMapping("/rebuild") java.util.Map<String,Integer> rebuild(@AuthenticationPrincipal AuthenticatedPrincipal p,@PathVariable Long knowledgeBaseId){return java.util.Map.of("reindexedChunks",rebuild.rebuild(p.tenantId(),knowledgeBaseId));}
 @GetMapping("/{documentId}") DocumentIngestionProgress getProgress(@AuthenticationPrincipal AuthenticatedPrincipal p,@PathVariable Long knowledgeBaseId,@PathVariable Long documentId){return progress.get(p.tenantId(),knowledgeBaseId,documentId);}}
