/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_v1_tickets_get"];
        put?: never;
        /** Submit Ticket */
        post: operations["submit_ticket_api_v1_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_api_v1_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drafts
         * @description 列出工单的全部草稿版本（按版本升序）。可见性由工单归属在服务端强制。
         */
        get: operations["list_drafts_api_v1_tickets__ticket_id__drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Draft
         * @description 人工编辑当前活动草稿：派生新版本（author=human），旧版本归档。
         *
         *     仅坐席与管理员可编辑；需要 CSRF 与幂等键。相同键 + 相同内容重放返回首次结果。
         */
        patch: operations["edit_draft_api_v1_tickets__ticket_id__drafts__draft_id__patch"];
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/drafts/{draft_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Draft
         * @description 把当前活动草稿发布为给客户的正式回复（终态 PUBLISHED）。
         *
         *     仅坐席与管理员可发布；需要 CSRF 与幂等键。条件更新保证并发发布只有一次生效。
         */
        post: operations["publish_draft_api_v1_tickets__ticket_id__drafts__draft_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Document */
        post: operations["import_document_api_v1_knowledge_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_knowledge_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import History */
        post: operations["import_history_api_v1_history_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Model Configs */
        get: operations["list_model_configs_api_v1_model_configs_get"];
        put?: never;
        /** Create Model Config */
        post: operations["create_model_config_api_v1_model_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Model Config */
        patch: operations["update_model_config_api_v1_model_configs__config_id__patch"];
        trace?: never;
    };
    "/api/v1/model-configs/{config_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable Model Config
         * @description 启用该配置。同类能力的其他配置会在同一事务内被停用。
         */
        post: operations["enable_model_config_api_v1_model_configs__config_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-configs/{config_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Model Config */
        post: operations["test_model_config_api_v1_model_configs__config_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Action Requests
         * @description 按状态列出操作申请。默认列出待审批。
         */
        get: operations["list_action_requests_api_v1_action_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action Request */
        get: operations["get_action_request_api_v1_action_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-requests/{request_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Action Ledger
         * @description 查询该申请的执行记录。账本只追加，没有删除接口。
         */
        get: operations["get_action_ledger_api_v1_action_requests__request_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-requests/{request_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Action Request
         * @description 批准或拒绝。
         *
         *     批准会**执行动作并写入账本**（同一事务），随后把运行推进到终态；
         *     拒绝只记录决策，不产生业务效果。
         */
        post: operations["decide_action_request_api_v1_action_requests__request_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Frozen Cases
         * @description 导入冻结评测集与语料（幂等）。
         */
        post: operations["import_frozen_cases_api_v1_evaluations_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Evaluation Run
         * @description 执行一次评测并落库指标。Mock 与真实模式的结果分别落库（AGENTS.md §10）。
         */
        post: operations["create_evaluation_run_api_v1_evaluations_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Run */
        get: operations["get_evaluation_run_api_v1_evaluations_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Evaluation Report
         * @description 导出 JSON 报告：聚合指标 + 逐用例结果。
         */
        get: operations["export_evaluation_report_api_v1_evaluations_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_tickets__ticket_id__runs_get"];
        put?: never;
        /**
         * Start Run
         * @description 人工发起一次新运行（不复活旧运行）。非坐席一律 403。
         */
        post: operations["start_run_api_v1_tickets__ticket_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionDecisionIn */
        ActionDecisionIn: {
            /**
             * Approve
             * @description true=批准并执行；false=拒绝
             */
            approve: boolean;
        };
        /**
         * ActionDecisionOut
         * @description 决策结果。
         *
         *     ``executed=False`` 且 ``blocked_reason="rejected"`` 表示**这是一次成功的拒绝**，
         *     不是错误；过期的申请会在决策时抛出 ``action_request_expired``（409）。
         */
        ActionDecisionOut: {
            request: components["schemas"]["ActionRequestOut"];
            /** Executed */
            executed: boolean;
            /** Blocked Reason */
            blocked_reason: string | null;
            ledger: components["schemas"]["ActionLedgerOut"] | null;
        };
        /** ActionLedgerOut */
        ActionLedgerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Action Request Id
             * Format: uuid
             */
            action_request_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /** Action Type */
            action_type: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
        };
        /** ActionRequestListOut */
        ActionRequestListOut: {
            /** Items */
            items: components["schemas"]["ActionRequestOut"][];
        };
        /** ActionRequestOut */
        ActionRequestOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Action Type */
            action_type: string;
            /** Status */
            status: string;
            /** Reason */
            reason: string;
            /** Ticket Version */
            ticket_version: number;
            /** Target Assignee Id */
            target_assignee_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Version */
            version: number;
        };
        /** Body_import_document_api_v1_knowledge_imports_post */
        Body_import_document_api_v1_knowledge_imports_post: {
            /** File */
            file: string;
        };
        /** Body_import_history_api_v1_history_imports_post */
        Body_import_history_api_v1_history_imports_post: {
            /** File */
            file: string;
        };
        /** ConnectionTestOut */
        ConnectionTestOut: {
            /** Ok */
            ok: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Model Name */
            model_name: string;
            /** Error Code */
            error_code?: string | null;
            /** Detail */
            detail?: string | null;
        };
        /**
         * DraftDetailOut
         * @description 一条草稿版本。``citations`` 是结构化引用快照（来源/编号/原文）。
         */
        DraftDetailOut: {
            /** Id */
            id: string;
            /** Ticket Id */
            ticket_id: string;
            /** Version */
            version: number;
            /** Author */
            author: string;
            /** Content */
            content: string;
            /** Citations */
            citations: {
                [key: string]: unknown;
            }[];
            /** Status */
            status: string;
            /** Editor User Id */
            editor_user_id: string | null;
            /** Run Id */
            run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Published At */
            published_at: string | null;
            /** Published By */
            published_by: string | null;
        };
        /** DraftEditRequest */
        DraftEditRequest: {
            /** Content */
            content: string;
        };
        /** EvaluationImportOut */
        EvaluationImportOut: {
            /** Created */
            created: number;
            /** Reused */
            reused: number;
            /** Corpus Docs */
            corpus_docs: number;
        };
        /**
         * EvaluationRunCreateIn
         * @description 执行一次评测。``mode`` 决定分类走 Mock 还是真实网关。
         */
        EvaluationRunCreateIn: {
            /**
             * Mode
             * @default mock
             */
            mode: string;
            /** Limit */
            limit?: number | null;
        };
        /** EvaluationRunOut */
        EvaluationRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Index Version */
            index_version: string;
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            } | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportJobOut */
        ImportJobOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Source Name */
            source_name: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Index Version */
            index_version: string;
            /** Duplicate */
            duplicate: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ModelCapability
         * @description 聊天与 Embedding **分别配置**（PLAN.md §3）。
         * @enum {string}
         */
        ModelCapability: "CHAT" | "EMBEDDING";
        /** ModelConfigCreateIn */
        ModelConfigCreateIn: {
            capability: components["schemas"]["ModelCapability"];
            /** @default OPENAI_COMPATIBLE */
            protocol: components["schemas"]["ModelProtocol"];
            /** Base Url */
            base_url: string;
            /** Model Name */
            model_name: string;
            /** Api Key */
            api_key: string;
            /** Embedding Dim */
            embedding_dim?: number | null;
        };
        /** ModelConfigListOut */
        ModelConfigListOut: {
            /** Items */
            items: components["schemas"]["ModelConfigOut"][];
        };
        /** ModelConfigOut */
        ModelConfigOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            capability: components["schemas"]["ModelCapability"];
            protocol: components["schemas"]["ModelProtocol"];
            /** Base Url */
            base_url: string;
            /** Model Name */
            model_name: string;
            /** Api Key Configured */
            api_key_configured: boolean;
            /** Embedding Dim */
            embedding_dim: number | null;
            /** Enabled */
            enabled: boolean;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ModelConfigUpdateIn
         * @description 局部更新。``api_key`` 省略表示保持原密钥不变。
         */
        ModelConfigUpdateIn: {
            /** Base Url */
            base_url?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Embedding Dim */
            embedding_dim?: number | null;
        };
        /**
         * ModelProtocol
         * @description 首版只支持 OpenAI-compatible 协议。
         * @enum {string}
         */
        ModelProtocol: "OPENAI_COMPATIBLE";
        /** PrincipalOut */
        PrincipalOut: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Is Staff */
            is_staff: boolean;
        };
        /** RunListOut */
        RunListOut: {
            /** Items */
            items: components["schemas"]["RunOut"][];
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Ticket Id */
            ticket_id: string;
            /** Status */
            status: string;
            /** Model Mode */
            model_mode: string;
            /** Chat Model Name */
            chat_model_name: string | null;
            /** Error Code */
            error_code: string | null;
            /** Step Count */
            step_count: number;
            /** Tool Call Count */
            tool_call_count: number;
            /** Retry Of Run Id */
            retry_of_run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** SearchOut */
        SearchOut: {
            /** Source Type */
            source_type: string;
            /** Source Id */
            source_id: string;
            /** Source Version */
            source_version: string;
            /** Chunk Id */
            chunk_id: string | null;
            /** Locator */
            locator: string;
            /** Quote Text */
            quote_text: string;
            /** Rank No */
            rank_no: number;
            /** Score */
            score: number;
            /** Full Text Rank */
            full_text_rank: number | null;
            /** Vector Rank */
            vector_rank: number | null;
        };
        /** SearchPageOut */
        SearchPageOut: {
            /** Query */
            query: string;
            /**
             * Mode
             * @default mock
             */
            mode: string;
            /** Items */
            items: components["schemas"]["SearchOut"][];
        };
        /** StartRunRequest */
        StartRunRequest: {
            /** Model Mode */
            model_mode?: string | null;
        };
        /** TicketCreateRequest */
        TicketCreateRequest: {
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Model Mode */
            model_mode?: string | null;
        };
        /**
         * TicketDetailOut
         * @description 详情额外返回清洗后的正文、乐观锁版本号，以及草稿链与已发布回复。
         *
         *     只返回 ``body_cleaned``：原始正文仅用于留档与审计，不通过接口外泄
         *     （其中可能混有用户误粘贴的敏感内容）。草稿里的 ``citations`` 是服务端从**本次
         *     检索结果**快照下来的可溯源引用，前端不得伪造来源。
         */
        TicketDetailOut: {
            /** Id */
            id: string;
            /** Ticket No */
            ticket_no: string;
            /** Subject */
            subject: string;
            /** Category */
            category: string | null;
            /** Category Label */
            category_label: string | null;
            /** Status */
            status: string;
            /** Assignee Id */
            assignee_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Body Cleaned */
            body_cleaned: string;
            /** Clean Version */
            clean_version: number;
            /** Version */
            version: number;
            /** Drafts */
            drafts: components["schemas"]["DraftDetailOut"][];
            /** Published Reply */
            published_reply: string | null;
        };
        /** TicketOut */
        TicketOut: {
            /** Id */
            id: string;
            /** Ticket No */
            ticket_no: string;
            /** Subject */
            subject: string;
            /** Category */
            category: string | null;
            /** Category Label */
            category_label: string | null;
            /** Status */
            status: string;
            /** Assignee Id */
            assignee_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Closed At */
            closed_at: string | null;
        };
        /** TicketPageOut */
        TicketPageOut: {
            /** Items */
            items: components["schemas"]["TicketOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * TicketStatus
         * @enum {string}
         */
        TicketStatus: "OPEN" | "CLOSED";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalOut"];
                };
            };
        };
    };
    list_tickets_api_v1_tickets_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TicketStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_ticket_api_v1_tickets_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_v1_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_v1_tickets__ticket_id__drafts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetailOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_draft_api_v1_tickets__ticket_id__drafts__draft_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                ticket_id: string;
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_draft_api_v1_tickets__ticket_id__drafts__draft_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                ticket_id: string;
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_document_api_v1_knowledge_imports_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_document_api_v1_knowledge_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_knowledge_search_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_history_api_v1_history_imports_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_history_api_v1_history_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_model_configs_api_v1_model_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigListOut"];
                };
            };
        };
    };
    create_model_config_api_v1_model_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_config_api_v1_model_configs__config_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_model_config_api_v1_model_configs__config_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_config_api_v1_model_configs__config_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_action_requests_api_v1_action_requests_get: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRequestListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_request_api_v1_action_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_ledger_api_v1_action_requests__request_id__ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_action_request_api_v1_action_requests__request_id__decide_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_frozen_cases_api_v1_evaluations_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationImportOut"];
                };
            };
        };
    };
    create_evaluation_run_api_v1_evaluations_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRunCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_run_api_v1_evaluations_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_evaluation_report_api_v1_evaluations_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_tickets__ticket_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_tickets__ticket_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                /** @description 仅推送 id 大于该值的事件 */
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
